### ISSUE TITLE
4th Community Review of BDX Allocator

### ISSUE THREAD

**Issue by cryptoAmandaL** [filecoin-project/Allocator-Governance#235] opened 2024-11-28 11:50 UTC
First Review https://github.com/filecoin-project/Allocator-Governance/issues/20
Second Review https://github.com/filecoin-project/Allocator-Governance/issues/142

Third Review https://github.com/filecoin-project/Allocator-Governance/issues/191

Latest Allocator Compliance Review https://compliance.allocator.tech/report/f03018484/1732754934/report.md

Given 2.5PiBs
DataCap was given to:
https://github.com/cryptoAmandaL/BDE-Allocator/issues/26(1.5PiB)
https://github.com/cryptoAmandaL/BDE-Allocator/issues/28(1PiB)

[26](https://github.com/cryptoAmandaL/BDE-Allocator/issues/26)
This client is applicant from [the previous application](https://github.com/cryptoAmandaL/BDE-Allocator/issues/22).

Since the client's storage plan has not yet been completed, the client would like to fix the previous problem and continue to come in and request datacap to complete the storage.
Client claimed to have stopped working with unqualified sps. And they have already provided their next list of sps.
After confirming the list, we think we can expect this client to do well in the future. Because we've seen the progress of this client in the last round.

**_This client came to request for applying a new application._**

![image](https://github.com/user-attachments/assets/de1221eb-c517-4427-97b4-e4654427b2e4)

**_We have check the retrieval rate of their new application._**

![image](https://github.com/user-attachments/assets/ee8d38c5-9f3e-42bc-b154-b72f8e9bcb34)

Their latest cid report.
https://check.allocator.tech/report/cryptoAmandaL/BDE-Allocator/issues/26/1732791379060.md

[28](https://github.com/cryptoAmandaL/BDE-Allocator/issues/28)
This client is applicant from [the previous application](https://github.com/cryptoAmandaL/BDE-Allocator/issues/18).

Last week we came to check the cid report to see their latest condition. We found that they have stopped their plan in August.
They said they still wanted to continue the storage and they looked for new sps within two months of the program's suspension.
**_We let them provide the new sp list._**
![image](https://github.com/user-attachments/assets/67f3699c-6fd3-4f30-9e63-76f532622778)

![image](https://github.com/user-attachments/assets/70ea4812-9cc9-4dec-b854-6b7a81d50393)

**_After checking the retrieval, we decided to give them a chance._**

![image](https://github.com/user-attachments/assets/4c86a28c-4279-4000-a949-d3e17c35f122)

Their latest cid report.
https://check.allocator.tech/report/cryptoAmandaL/BDE-Allocator/issues/28/1732762500567.md

**_We have asked for the reason of one sp with low retrieval in their report._**

![image](https://github.com/user-attachments/assets/79c5b4cc-fb29-46be-bb08-dfec74085a32)

**_They have stopped to send data to this sp after sent a little data._**
![image](https://github.com/user-attachments/assets/4ceea5f1-234f-4b45-8b88-04fca42bd4a5)

**_After confirmed their report, e decided to allocate a smaller amount than originally planned for the expected change in client._**
![image](https://github.com/user-attachments/assets/8ce1ba64-671b-418d-9fe4-d4b8328ccfa6)

We are making ongoing improvements to our work as an allocator. We would like to have support from fil+ community.

**Comment by filecoin-watchdog** [comment] 2024-12-04 18:40
@cryptoAmandaL 
[Allocator Application](https://github.com/filecoin-project/notary-governance/issues/1027)  
[Compliance Report](https://compliance.allocator.tech/report/f03018484/1733273057/report.md) 
[1st Review](https://github.com/filecoin-project/Allocator-Governance/issues/20)  
[2nd Review](https://github.com/filecoin-project/Allocator-Governance/issues/142)  
[3rd Review](https://github.com/filecoin-project/Allocator-Governance/issues/191)  
1st Review score: 2.5PiB
2nd Review score: 2.5PiB
3rd Review score: 2.5PiB

2.5 PiB granted to existing clients:
| Client Name | DC | status |
| -------- | ------- | ------- |
| ESGFand Pangeo | 1.5PiB | New |
| NOAA | 1PiB | New |

[ESGF and Pangeo](https://github.com/cryptoAmandaL/BDE-Allocator/issues/26)
* I understand your decision to give this client another chance, but why are you using the same dataset? In the previous report, I noted that this dataset had already been stored multiple times. Despite this, it was agreed to store it again without any explanation provided in the application form or by the allocator in the issue. There is no clear reason for storing additional copies, nor has it been justified.
* This is essentially the same application as # 22. Once again, the numbers are inconsistent: the client requested 5 PiBs but declared 10 replicas of a 1792 TiB dataset.
* The SPs (Storage Providers) used for the deals match the provided or updated list. However, 2 out of the 8 SPs have very low retrieval rates.
* The requirement for four geopolitical regions has not been met. Currently, only China, Hong Kong, and Singapore are included.

[NOAA](https://github.com/cryptoAmandaL/BDE-Allocator/issues/28)
* This application also has inaccurate numbers: the client requested 5 PiBs but declared 10 replicas of a 612 TiB dataset.
* This dataset has already been stored multiple times before (aside from your previous cooperation with this client). See these references: [LDN](https://github.com/search?q=repo%3Afilecoin-project%2Ffilecoin-plus-large-datasets+noaa-nbm-grib2-pds&type=issues), [allocator.tech](https://github.com/sxxfuture-official/filplus-allocator-sxxfuture/issues/18)
* Five SPs were used for the deals. Among them, one has a retrieval rate of less than 1%, and another has a rate below 20%. * The remaining SPs have high retrieval rates.
* The requirement for four geopolitical regions has not been fulfilled. Currently, only China and Hong Kong are covered.

---

Has the allocator made any progress towards a manual allocator? Has anything changed in that regard?

**Comment by cryptoAmandaL** [comment] 2024-12-05 10:46
@filecoin-watchdog Hello!

These two applications can be seen as a continuation of the previous two applications [#22](https://github.com/cryptoAmandaL/BDE-Allocator/issues/22) and [#18](https://github.com/cryptoAmandaL/BDE-Allocator/issues/18), as clients have made progress in their previous jobs and we want to give them another chance.

https://github.com/cryptoAmandaL/BDE-Allocator/issues/26

The client has mentioned that they would like to correct the data of retrieval in the report and would like to remove the sp that has stopped cooperation in the report.
![image](https://github.com/user-attachments/assets/4c818fdc-c49c-4ff6-9e5d-3c4c7fb51b99)
We felt that it was a reasonable proposal and agreed that the client could submit a new application to continue their previously unfinished data storage plan.

But before continuing to allocate to the client, we did a review of the client's next steps of sps.
We checked the results of the sps on spark based on their latest sp list provided by the client.
![image](https://github.com/user-attachments/assets/29c2873a-9f19-45e1-aed8-418ab45b84e0)
After confirming that the client's sps were in support of the retrieval, we decided to allow the client to go ahead.



https://github.com/cryptoAmandaL/BDE-Allocator/issues/28


This client had interrupted their process at the end of August.
When we confirmed with the client whether to close their application, we learned that the client had spent two months looking for new sps to try to continue with their previous plan.
![image](https://github.com/user-attachments/assets/bb3c8b41-3c8d-4bfa-9f88-6c273c237539)

In the same way, we asked the client to provide the list of new sps they found, and confirmed on spark about the retrieval rate.
![image](https://github.com/user-attachments/assets/3e796b9a-e7a0-4c63-956b-6076e4f6bf57)

After getting the retrieval results, we suggested to the client to submit a new application for separating the history of no longer cooperating with the sps.


Regarding the question of whether their requested amount of applications for the two clients matches the number of copies they store, our idea is that they had been allocated datacap and stored some data, and as a continuation of the previous applications, they would need less datacap than their original plan.



>The requirement for four geopolitical regions has not been met. Currently, only China, Hong Kong, and Singapore are included.

>The requirement for four geopolitical regions has not been fulfilled. Currently, only China and Hong Kong are covered.

Considering that the above two clients haven't finished storing all the replicas yet, we will remind the clients to pay attention to the selection of the storage area in the next process, thanks for your reminder!


After our previous experience, we have become more strict in our review of our clients, and we will check the retrieval of the sps provided by our clients in advance. And we need to see the progress our clients are making. When we find out that our clients are meeting problems, we help and ask them to solve it as soon as possible.

Comparing the data from yesterday and today, we are seeing more obvious change and improvement in our clients, which we believe is a step forward that we are making with our clients.
[#26](https://github.com/cryptoAmandaL/BDE-Allocator/issues/26)
yesterday in report https://check.allocator.tech/report/cryptoAmandaL/BDE-Allocator/issues/26/1733335548897.md
![image](https://github.com/user-attachments/assets/20ab98f4-3a1e-4ab0-a8f7-4b7ce0de3811)
today on spark
![image](https://github.com/user-attachments/assets/5ce93b51-23da-4f72-937d-56d2f61d8d29)

[#28](https://github.com/cryptoAmandaL/BDE-Allocator/issues/28)
yesterday in report https://check.allocator.tech/report/cryptoAmandaL/BDE-Allocator/issues/28/1733337002820.md
![image](https://github.com/user-attachments/assets/2d7512b0-1a44-4a7f-911d-a34e64d6dd84)
today on spark
![image](https://github.com/user-attachments/assets/7e1d614b-4346-4f91-a941-04e7425cad5a)

We're trying harder to do a better job in the allocator role. Hope gov team will see the progress we're making and support us to do more for FIl+.

Thank you for the hardworking to every one!

**Comment by galen-mcandrew** [comment] 2024-12-06 06:40
The evidence and diligence provided is helpful, which shows that the allocator is attempting to hold clients accountable to requirements, such as retrieval. However, this is now the 4th review, with all three previous compliance reviews showing relatively similar results. Specifically:

- Noncompliant and inaccurate regional distribution, with VPNs unaccounted for 
- No additional details regarding dataset preparation, especially with these redundant datasets
- Overall retrieval still below 25%

These flags have been brought up multiple times, and while we understand there can be some delays in improvement, we have quite a few successful manual allocators. Additionally, there are new teams that are eager to join the program and have already shown success collaborating with allocators. At this point, the governance team is going to intervene and reject this application. **We are requesting the RKH to remove this pathway.**

While the above flags are an issue, the largest contributing factor to our decision to not renew this pathway has to do with fundamentally **not delivering on their initial application** to build a market-based program. @cryptoAmandaL the community still needs market-based, smart contract driven, tools to support data exchange. We look forward to seeing a future application with some testable MVP tools for clients and storage providers.

**Comment by cryptoAmandaL** [comment] 2024-12-06 11:09
@galen-mcandrew 

We do not agree with this result. 
We ask to keep our eligibility as allocator.
We do not accept the unfair treatment, which should not be allowed in the fil+ community.


1. We think there's some wrong in your conclusion.

>Noncompliant and inaccurate regional distribution, with VPNs unaccounted for

We have communicated about this problem in our [second review](https://github.com/filecoin-project/Allocator-Governance/issues/142).
Here's the record.
https://github.com/filecoin-project/Allocator-Governance/issues/142#issuecomment-2340043273
![image](https://github.com/user-attachments/assets/13a2da0d-5066-44ab-9f0b-ae2e7c957ace)
https://github.com/filecoin-project/Allocator-Governance/issues/142#issuecomment-2346859273
![image](https://github.com/user-attachments/assets/224fa12e-aee6-478a-9240-d5df8b374f09)
https://github.com/filecoin-project/Allocator-Governance/issues/142#issuecomment-2348504892
![image](https://github.com/user-attachments/assets/5985b165-61e7-41f7-bbf6-b5b76e0cd3fe)


We are always looking for good tools to help us or other allocators who are having the same require recognize sp's attribute.
We believe that each allocator's standard can be considered accurate until there is a standardization tool to provide a standard answer.



>No additional details regarding dataset preparation, especially with these redundant datasets

We do not believe that public academic datasets are superior or inferior. That's why we welcome all kinds of data from legitimate sources from our clients. 

Nowadays, all alloctors are allowing redundant datasets. The value of data should not be denied based on the number of times it has been stored.

Can the community give us some ideas? 

If allocator can't follow its own criteria for accepting data, what's the best way to accept clients?



>Overall retrieval still below 25%

Can you please tell us how to get the result?

Here's the latest report. From previous report and the latest report, the overall retrieval rates are both higher than 25%.
https://check.allocator.tech/report/cryptoAmandaL/BDE-Allocator/issues/26/1733472599300.md
![image](https://github.com/user-attachments/assets/b5fa90ca-5434-4be1-8367-e1484d1cab8d)

https://check.allocator.tech/report/cryptoAmandaL/BDE-Allocator/issues/28/1733472604920.md
![image](https://github.com/user-attachments/assets/60e26253-7b87-47c4-ad66-e9694b84da10)


When sps meet problems, they need time to resolve that.

Also, the data in report is hysteretic. We usually get accurate results from spark dashboard.

This sp in report has got only 9% of successful retrieval rate. The result I got from spark is 86% one minute ago.
![image](https://github.com/user-attachments/assets/007d04a9-1f43-4afe-978a-e10b8ed67ffb)


2. There are a number of allocators claimed their type is market-based, and no successful one has been seen yet.

Allocator is a totally new experiment for the Fil+ community. Every one is exploring and improving on how to be better as an allocator. Why is it only unfair to us?



3. If your conclusion is not corrected this time, we'll keep feeding and complaining in community.

We think that it is a web3 community here.

Decision-making can be voted by community members, rather than individual preferences governing everything. This is not a stage for dictators.


Expect to receive a response.

**Comment by filecoin-watchdog** [comment] 2024-12-09 07:50
@cryptoAmandaL 
>We do not believe that public academic datasets are superior or inferior. That's why we welcome all kinds of data from legitimate sources from our clients.

1. As an allocator, your primary focus should be ensuring the quality and value of datasets stored on Filecoin. Your current approach seems to prioritize accommodating all clients rather than enhancing network quality. This isn’t about whether the data itself is good or bad—that wasn’t part of the assessment. My review explicitly highlighted that this was the _nth_ duplicate of the same data, which should not occur on-chain without a clear and justified reason.
The application form includes a section where clients can explain why they are storing the same data again. In both cases here, those answers were left blank. This also occurred during their original application. The fact that they are ongoing clients of yours is irrelevant in this context because it does not justify the lack of explanations.


2. In your response, you stated:

>(…) our idea is that they had been allocated datacap and stored some data (…)

2. This demonstrates a pattern in your reviews where assumptions about client actions replace direct inquiries. As a validator, it is your responsibility to ask the necessary questions when discrepancies arise. Your role is to ensure clarity and accountability, not to rely on assumptions. When something in an application appears inconsistent, it is the client’s obligation to provide an explanation, not yours. I pointed this out during the previous review, yet you continue to insist on this approach.



>There are a number of allocators claimed their type is market-based, and no successful one has been seen yet.
Allocator is a totally new experiment for the Fil+ community. Every one is exploring and improving on how to be better as an allocator. Why is it only unfair to us?

3. You chose to become an allocator and committed to delivering on certain promises. When those commitments aren’t met, pointing to perceived unfair treatment does not absolve you of accountability. It is equally unfair to make promises, avoid addressing them when questioned, and deflect by referencing others who have not yet faced consequences for similar issues.
Additionally, you have not presented a clear plan for transitioning into a market-based allocator model. The only clarification you’ve provided is that you cannot currently achieve that goal. At this stage, you should operate as a fully transparent manual allocator to demonstrate the value you bring to the network. Instead, you continue to introduce your own rules, which neither enhance network quality nor encourage improved client behavior.

4. Regarding the retrieval issue you mentioned: as an allocator, you should be actively pushing your clients to address low retrieval success rates and maintaining evidence of those efforts in the relevant GitHub issues. Without the potential consequence of losing future datacap allocations, there’s little motivation for clients to comply. Ensuring accountability is essential to maintaining the integrity and quality of the network.

**Comment by cryptoAmandaL** [comment] 2024-12-09 10:28
@filecoin-watchdog 
As a allocator who need to serve clients, on the condition that the client provides the information and meets the retrieval as requested, we think the allocator can follow the their own rules for making decisions about the client.
We've been learning in the Fil+ community for a long time and have seen changes in the community. A majority of allocators today don't do what they said they would do to complete the review and allocation to clients.
Such as this allocator - NonEntropy. They confused the gov team for more datacap in the name of building a tool that was initially just a tool for themselves to be able to show their sp retrieval rates, isn't that something that should be scrutinized in detail? Why were they allowed to be granted 20PiB when the retrieval results were so bad?
![image](https://github.com/user-attachments/assets/52bafbfb-35a0-480e-acef-ecef671b543d)
![image](https://github.com/user-attachments/assets/5ab4a069-e06d-4be2-89df-c36055385aee)
![image](https://github.com/user-attachments/assets/22e4fdda-66d7-445b-a4e1-bcbfb0d0b254)
All of the above data comes from their cid report. https://compliance.allocator.tech/report/f03018029/1731979795/report.md

That's what we mean by unfairness. The community should treat every allocator with a rigorous standard and provide timely guidance to allocators. Although we were granted 4 rounds, the amount granted was much less than what the others were given in one round. Shouldn't this be something the gov team needs to treat equally? It would be equally unfair to judge us merely on the basis of the number of rounds granted.

**Comment by filecoin-watchdog** [comment] 2024-12-09 11:35
@cryptoAmandaL 
I’m not willing to discuss other allocators here. My reviews are conducted impartially, and I weigh non-compliance issues equally across all cases. While you have demonstrated some improvements throughout your four allocations, addressing one issue at a time especially when issues with your pathway were directly pointed out shows that there is not enough action being taken towards proper improvement.

From the beginning, your pathway has not been fully compliant, and you’ve been given multiple opportunities to make meaningful improvements. We never asked you to achieve the impossible — we've seen allocators who successfully addressed concerns raised during reviews and made significant progress.

Your responses to my review notes, along with your incremental improvements to the summary points from previous reviews, were insufficient to demonstrate the necessary level of compliance. This led to the rejection, which you were already warned about during the third review.

Galen has emphasized on multiple occasions that building your own tooling, which can then be shared and utilized by the community, is highly encouraged. Bringing up what another allocator has done to improve the network feels a bit out of place in this context. But as I already mentioned, I’m not willing to discuss other allocators here, so I’ll leave it at that.

**Comment by cryptoAmandaL** [comment] 2024-12-10 07:24
@filecoin-watchdog 
Why can't we discuss other allocators here?
Or should it be discussed on slack?

Your comments confirm exactly what I said about unfairness. I think it's time to get Juan and Molly to judge it. Your unfair treatment has caused a huge blow to allocators who were willing to bring data and clients to filecoin. We demand that the gov team must make a formal and effective response to deal with this issue. There are various obvious examples of unfairness within the community, which is why the development of fil+ is stagnating or even going backwards.

**Comment by martapiekarska** [comment] 2024-12-10 09:24
Hi @cryptoAmandaL just putting my 2 cents in 
- if you want to discuss behaviour of other allocators - do it on their review page. 
- the fil+ program is governed by Filecoin Foundation, and specifically by the governance team of the Fil+ program. Molly and Juan are, in this case, members of the community and can express their views just like you, me or watchdog.

**Comment by filecoin-watchdog** [comment] 2024-12-10 10:18
I don't have anything new to add aside from repeating myself with what has already been said. As @martapiekarska rightly mentioned above, this is _your_ review issue, and our focus remains on discussing _your_ case, not others. Let’s keep this discussion clear and on-topic to avoid mess.

**Comment by galen-mcandrew** [comment] 2024-12-10 19:34
@cryptoAmandaL can you please clarify and define your role with BDX? Based on some conversations we have had with other teams, that entire program and project was sunset and no longer operating.

**Comment by Kevin-FF-USA** [comment] 2024-12-10 23:24
Friendly hello,

If helpful - created a discussion issue https://github.com/filecoin-project/Allocator-Governance/discussions/246 to hopefully unify some of the threads and questions from this issue and SLACK.

**Comment by cryptoAmandaL** [comment] 2024-12-11 11:32
@martapiekarska OK. I'll do that.

@galen-mcandrew I'm one of BDX. It's true that our previous project has ended. Then some of us intended to continue to be deeply participating in the filecoin community and contributing to fil+ building. So we are still here.

@Kevin-FF-USA Thank you.

**Comment by galen-mcandrew** [comment] 2024-12-12 16:56
Based on your own admission, and corroborated by other members of the community connected to BDX, that program is no longer in operation or developing tooling for data onboarding. 

We do not even need to review, discuss, or justify the issues raised around this allocator's onboarding (retrieval, replicas, distribution, etc). The fundamental reason this allocator will not be receiving additional DataCap relates to the significant departure from the original stated [application](https://github.com/filecoin-project/notary-governance/issues/1027).

You have made it clear that you are not operating as BDX or developing those data onboarding tools. Therefore, you as an individual or team of former employees are not in the position to run this allocator under this name or description. You are welcome to reapply with an updated, accurate, and transparent set of responses, which may allow you to be in compliance. We have multiple allocators that function as engaged community members.

There is nothing left to discuss on this issue. It is a clear case that the allocator pathway is no longer in compliance with it's original application, which cannot be rectified as that company and project are no longer active.

**Closed** 2024-12-12 18:15 UTC
Labels: Awaiting Response from Allocator, Refresh
